//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SREZ_1.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> ProvideServiceID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public double Result { get; set; }
        public byte[] Finished { get; set; }
        public bool Accepted { get; set; }
        public string Status { get; set; }
        public string Analyzer { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ProvideService ProvideService { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
