//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SREZ_1.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvideService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProvideService()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ProvideServiceID { get; set; }
        public int PatientID { get; set; }
        public int BarCode { get; set; }
        public byte[] Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
